version: '3.8'
services:
  application:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=mongodb://mongodb:27017/cognigy
      - PORT=3000
      - API_KEY=dK9WBV5H@7
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db